### ISSUE TITLE
Prep for Homebrew

### ISSUE THREAD

**Issue by jasonm23** [haosdent/s#5]

**Comment by haosdent** [comment]
ok, let me add this. Thank you for you advice. :-)

**Comment by jasonm23** [comment]
Thank you

**Comment by jasonm23** [comment]
I recommend you tag commit as 0.1.0 and use github's archive facility to generate a tar.gz release.

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/z.rb

Should be a useful guide

**Comment by haosdent** [comment]
I create this pull request Homebrew/homebrew#37362 . Let homebrew committers help us to review it. Thank you for your great advice again. :-)

**Comment by haosdent** [comment]
And we could install it from brew through:

```
brew install https://raw.githubusercontent.com/haosdent/homebrew/master/Library/Formula/s.rb
```

**Comment by jasonm23** [comment]
If it takes a long time to get integrated you can setup a brew tap.

A brew tap is a github repo with its own formulas.

See https://github.com/railwaycat/homebrew-emacsmacport for an example

**Comment by haosdent** [comment]
Thank you for your link. I create [haosdent/homebrew-s](https://github.com/haosdent/homebrew-s) . So we could install it through:

```
brew tap haosdent/s && brew install s
```

Thank you very much again for your great help. :+1:
