### ISSUE TITLE
Detect usages of ssh with an alias. 

### ISSUE THREAD

**Issue by Firewall** [haosdent/s#7]
Currently I use ssh with alias'es so that I don't always have to type out the username. 

For example:
`alias ssr="ssh -l root $*"`

This allows me to go `ssr hostname.com` and it will connect me with the user root. This however isn't detected by s

**Comment by haosdent** [comment]
hmmm, it is a problem. Let me think if a better way to solve this.

**Comment by haosdent** [comment]
I fixed this now, help try again. Thank you for your repo. :-)

**Comment by Firewall** [comment]
Fix worked, thanks!

**Comment by haosdent** [comment]
@Firewall thank you for your feedback again. You are welcome. :-)
