### ISSUE TITLE
frecency should be frequency

### ISSUE THREAD

**Issue by savingschampion** [haosdent/s#9]
inb4 you get ripped apart by reddit :P

**Comment by savingschampion** [comment]
unless this is what you mean, in which case adding a link may be helpful...

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm

**Comment by haosdent** [comment]
Thank you for your advice, let me update it. Frecency is a new word. http://en.wikipedia.org/wiki/Frecency
